### ISSUE TITLE
Audio files not created or not reachable on Vercel?

### ISSUE THREAD

**Issue by quacrobat** [supershaneski/openai-whisper-api#4]
Hello, 
Thank you for the hard work and effort you put in sharing this with excellent documentation.
I have successfully managed to install and run it with API on localhost.
But i would like to deploy it to Vercel (which most NextJs developers will want to use), and while the build successfully deploys and the page loads, it returns an error when i try to transcribe:
```
- error Error: ENOENT: no such file or directory, open 'public/uploads/file168369759598641389.webm'
```
I suppose this is related to how NextJs deals with the public folder path (as a source for copying files during build, not as an actual subfolder, so theoretically the correct path for the file on a live server should be 'uploads/file168369759598641389.webm' - i think!

Or is this relevant: [https://vercel.com/guides/how-to-upload-and-store-files-with-vercel](https://vercel.com/guides/how-to-upload-and-store-files-with-vercel) ? Perhaps it's something else and the files should be uploaded to a CDN or S3? that would be an amazing feature to have.

**Comment by quacrobat** [comment]
Found a workaround but it breaks the possibility of re-listening to the audio recordings or keeping them long term (unless associated with an upload to AWS S3 for example):

👉 Replace `public/uploads/` with `/tmp/`. 

Note, this is for **Vercel**/serverless hosting and should not be needed in basic hosting settings.

**Comment by quacrobat** [comment]
I'll close this issue for now. 

@supershaneski or anyone else please feel free to reopen and thanks again for a great repo.

**Comment by supershaneski** [comment]
Thank you for the heads up.

I was also looking at fixing this from different angle. Instead of saving the file, I am thinking of using the buffer data directly. I found some leads but not yet tested:

https://stackoverflow.com/a/62678816

As for re-playing the audio data, you can probably save the Blob to the localStorage before sending it to the back end. Then to play it, use dataURL:

```
var dataURL = window.URL.createObjectURL(blob);
var audio = new Audio(dataURL);
audio0.play();
```

**Comment by trevhud** [comment]
> Found a workaround but it breaks the possibility of re-listening to the audio recordings or keeping them long term (unless associated with an upload to AWS S3 for example):
> 
> 👉 Replace `public/uploads/` with `/tmp/`.
> 
> Note, this is for **Vercel**/serverless hosting and should not be needed in basic hosting settings.

Can you elaborate on this?

Does the tmp folder go in `/public` or root?
And then I need to modify the path in `whisper/route.js`?
